DELIMITER @
DROP TRIGGER IF EXISTS augmteLigneCommande ;
CREATE TRIGGER augmteLigneCommande
AFTER INSERT ON LIGNE_COMMANDE
FOR EACH ROW
BEGIN
UPDATE COMMANDE
SET nbligne = nbligne +1
WHERE COMMANDE.NUMERO = (SELECT DISTINCT NUMERO FROM LIGNE_COMMANDE WHERE NUMERO= NEW.numero);
END ;
@
DELIMITER ;



DROP TRIGGER IF EXISTS suppression ;
DELIMITER ///

CREATE TRIGGER suppression
BEFORE INSERT ON COMMANDE
FOR EACH ROW
BEGIN
	SET NEW.ligne_commande =  ;
END ;
///

DELIMITER ;